(cl:in-package gps_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          SATELLITES_USED-VAL
          SATELLITES_USED
          SATELLITE_USED_PRN-VAL
          SATELLITE_USED_PRN
          SATELLITES_VISIBLE-VAL
          SATELLITES_VISIBLE
          SATELLITE_VISIBLE_PRN-VAL
          SATELLITE_VISIBLE_PRN
          SATELLITE_VISIBLE_Z-VAL
          SATELLITE_VISIBLE_Z
          SATELLITE_VISIBLE_AZIMUTH-VAL
          SATELLITE_VISIBLE_AZIMUTH
          SATELLITE_VISIBLE_SNR-VAL
          SATELLITE_VISIBLE_SNR
          STATUS-VAL
          STATUS
          MOTION_SOURCE-VAL
          MOTION_SOURCE
          ORIENTATION_SOURCE-VAL
          ORIENTATION_SOURCE
          POSITION_SOURCE-VAL
          POSITION_SOURCE
))