(cl:in-package gps_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATUS-VAL
          STATUS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          TRACK-VAL
          TRACK
          SPEED-VAL
          SPEED
          CLIMB-VAL
          CLIMB
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          DIP-VAL
          DIP
          TIME-VAL
          TIME
          GDOP-VAL
          GDOP
          PDOP-VAL
          PDOP
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          TDOP-VAL
          TDOP
          ERR-VAL
          ERR
          ERR_HORZ-VAL
          ERR_HORZ
          ERR_VERT-VAL
          ERR_VERT
          ERR_TRACK-VAL
          ERR_TRACK
          ERR_SPEED-VAL
          ERR_SPEED
          ERR_CLIMB-VAL
          ERR_CLIMB
          ERR_TIME-VAL
          ERR_TIME
          ERR_PITCH-VAL
          ERR_PITCH
          ERR_ROLL-VAL
          ERR_ROLL
          ERR_DIP-VAL
          ERR_DIP
          POSITION_COVARIANCE-VAL
          POSITION_COVARIANCE
          POSITION_COVARIANCE_TYPE-VAL
          POSITION_COVARIANCE_TYPE
))