# Get list of all routes. Routes will contain metadata, but no points.

---
marti_nav_msgs/Route[] routes

bool success     # indicate successful run of triggered service
string message   # informational, e.g. for error messages
