string name      # Name for the route
string thumbnail # base64-encoded in caller defined format

---

bool success     # indicate successful run of triggered service
string message   # informational, e.g. for error messages
