# Set a route as active

string guid # GUID of route to make active, as 32 hex digits
bool repeat # If true, run the route repeatedly

---

bool success     # indicate successful run of triggered service
string message   # informational, e.g. for error messages
