// Generated by gencpp from file marti_nav_msgs/Command.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_COMMAND_H
#define MARTI_NAV_MSGS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : header()
    , startstop()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , startstop(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _startstop_type;
  _startstop_type startstop;





  typedef boost::shared_ptr< ::marti_nav_msgs::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::marti_nav_msgs::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::marti_nav_msgs::Command > CommandPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::Command_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::Command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.startstop == rhs.startstop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::Command_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "252763f31a786611d807254ade7c1dc3";
  }

  static const char* value(const ::marti_nav_msgs::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x252763f31a786611ULL;
  static const uint64_t static_value2 = 0xd807254ade7c1dc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/Command";
  }

  static const char* value(const ::marti_nav_msgs::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32[] startstop\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::marti_nav_msgs::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.startstop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::Command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "startstop[]" << std::endl;
    for (size_t i = 0; i < v.startstop.size(); ++i)
    {
      s << indent << "  startstop[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.startstop[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_COMMAND_H
