// Generated by gencpp from file marti_nav_msgs/GetRouteListRequest.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_GETROUTELISTREQUEST_H
#define MARTI_NAV_MSGS_MESSAGE_GETROUTELISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct GetRouteListRequest_
{
  typedef GetRouteListRequest_<ContainerAllocator> Type;

  GetRouteListRequest_()
    {
    }
  GetRouteListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRouteListRequest_

typedef ::marti_nav_msgs::GetRouteListRequest_<std::allocator<void> > GetRouteListRequest;

typedef boost::shared_ptr< ::marti_nav_msgs::GetRouteListRequest > GetRouteListRequestPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::GetRouteListRequest const> GetRouteListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/GetRouteListRequest";
  }

  static const char* value(const ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRouteListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::marti_nav_msgs::GetRouteListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_GETROUTELISTREQUEST_H
