// Generated by gencpp from file marti_nav_msgs/GetRouteList.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_GETROUTELIST_H
#define MARTI_NAV_MSGS_MESSAGE_GETROUTELIST_H

#include <ros/service_traits.h>


#include <marti_nav_msgs/GetRouteListRequest.h>
#include <marti_nav_msgs/GetRouteListResponse.h>


namespace marti_nav_msgs
{

struct GetRouteList
{

typedef GetRouteListRequest Request;
typedef GetRouteListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRouteList
} // namespace marti_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marti_nav_msgs::GetRouteList > {
  static const char* value()
  {
    return "24b443520442ddc540d0fd59f35403a5";
  }

  static const char* value(const ::marti_nav_msgs::GetRouteList&) { return value(); }
};

template<>
struct DataType< ::marti_nav_msgs::GetRouteList > {
  static const char* value()
  {
    return "marti_nav_msgs/GetRouteList";
  }

  static const char* value(const ::marti_nav_msgs::GetRouteList&) { return value(); }
};


// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteListRequest> should match
// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteList >
template<>
struct MD5Sum< ::marti_nav_msgs::GetRouteListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::GetRouteList >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::GetRouteListRequest> should match
// service_traits::DataType< ::marti_nav_msgs::GetRouteList >
template<>
struct DataType< ::marti_nav_msgs::GetRouteListRequest>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::GetRouteList >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteListResponse> should match
// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteList >
template<>
struct MD5Sum< ::marti_nav_msgs::GetRouteListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::GetRouteList >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::GetRouteListResponse> should match
// service_traits::DataType< ::marti_nav_msgs::GetRouteList >
template<>
struct DataType< ::marti_nav_msgs::GetRouteListResponse>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::GetRouteList >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_GETROUTELIST_H
