// Generated by gencpp from file marti_nav_msgs/GetRoute.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_GETROUTE_H
#define MARTI_NAV_MSGS_MESSAGE_GETROUTE_H

#include <ros/service_traits.h>


#include <marti_nav_msgs/GetRouteRequest.h>
#include <marti_nav_msgs/GetRouteResponse.h>


namespace marti_nav_msgs
{

struct GetRoute
{

typedef GetRouteRequest Request;
typedef GetRouteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRoute
} // namespace marti_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marti_nav_msgs::GetRoute > {
  static const char* value()
  {
    return "9f5c6eaa0139ef1e2690cdfe037b8e5e";
  }

  static const char* value(const ::marti_nav_msgs::GetRoute&) { return value(); }
};

template<>
struct DataType< ::marti_nav_msgs::GetRoute > {
  static const char* value()
  {
    return "marti_nav_msgs/GetRoute";
  }

  static const char* value(const ::marti_nav_msgs::GetRoute&) { return value(); }
};


// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteRequest> should match
// service_traits::MD5Sum< ::marti_nav_msgs::GetRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::GetRouteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::GetRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::GetRouteRequest> should match
// service_traits::DataType< ::marti_nav_msgs::GetRoute >
template<>
struct DataType< ::marti_nav_msgs::GetRouteRequest>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::GetRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marti_nav_msgs::GetRouteResponse> should match
// service_traits::MD5Sum< ::marti_nav_msgs::GetRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::GetRouteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::GetRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::GetRouteResponse> should match
// service_traits::DataType< ::marti_nav_msgs::GetRoute >
template<>
struct DataType< ::marti_nav_msgs::GetRouteResponse>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::GetRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::GetRouteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_GETROUTE_H
