// Generated by gencpp from file marti_nav_msgs/RouteSpeed.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_ROUTESPEED_H
#define MARTI_NAV_MSGS_MESSAGE_ROUTESPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct RouteSpeed_
{
  typedef RouteSpeed_<ContainerAllocator> Type;

  RouteSpeed_()
    : header()
    , id()
    , distance(0.0)
    , speed(0.0)  {
    }
  RouteSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , distance(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct RouteSpeed_

typedef ::marti_nav_msgs::RouteSpeed_<std::allocator<void> > RouteSpeed;

typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeed > RouteSpeedPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeed const> RouteSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.distance == rhs.distance &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f631b91ce4466a5134dc80c43e8d342";
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f631b91ce4466a5ULL;
  static const uint64_t static_value2 = 0x134dc80c43e8d342ULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/RouteSpeed";
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Speed at a position along route\n"
"\n"
"Header  header   # only stamp used\n"
"string  id       # unique ID of nearest point\n"
"float32 distance # forward along route, in meters from point identified by id\n"
"                 # field (negative values indicate the distance is backward\n"
"                 # along the route)\n"
"float32 speed    # desired speed at the specified position\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.distance);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RouteSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::RouteSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_ROUTESPEED_H
