// Generated by gencpp from file marti_nav_msgs/RoutePoint.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_ROUTEPOINT_H
#define MARTI_NAV_MSGS_MESSAGE_ROUTEPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <marti_common_msgs/KeyValue.h>

namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct RoutePoint_
{
  typedef RoutePoint_<ContainerAllocator> Type;

  RoutePoint_()
    : pose()
    , id()
    , properties()  {
    }
  RoutePoint_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , id(_alloc)
    , properties(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef std::vector< ::marti_common_msgs::KeyValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::marti_common_msgs::KeyValue_<ContainerAllocator> >::other >  _properties_type;
  _properties_type properties;





  typedef boost::shared_ptr< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> const> ConstPtr;

}; // struct RoutePoint_

typedef ::marti_nav_msgs::RoutePoint_<std::allocator<void> > RoutePoint;

typedef boost::shared_ptr< ::marti_nav_msgs::RoutePoint > RoutePointPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::RoutePoint const> RoutePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::RoutePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::RoutePoint_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RoutePoint_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.id == rhs.id &&
    lhs.properties == rhs.properties;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::RoutePoint_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RoutePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f627df35e7330c4ee0337ac3a4de9c";
  }

  static const char* value(const ::marti_nav_msgs::RoutePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f627df35e7330cULL;
  static const uint64_t static_value2 = 0x4ee0337ac3a4de9cULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/RoutePoint";
  }

  static const char* value(const ::marti_nav_msgs::RoutePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose           pose\n"
"string                       id         # unique identifier for this point\n"
"marti_common_msgs/KeyValue[] properties\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: marti_common_msgs/KeyValue\n"
"# An arbitrary key-value pair\n"
"\n"
"string key\n"
"string value\n"
;
  }

  static const char* value(const ::marti_nav_msgs::RoutePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.id);
      stream.next(m.properties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoutePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::RoutePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::RoutePoint_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "properties[]" << std::endl;
    for (size_t i = 0; i < v.properties.size(); ++i)
    {
      s << indent << "  properties[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marti_common_msgs::KeyValue_<ContainerAllocator> >::stream(s, indent + "    ", v.properties[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_ROUTEPOINT_H
