// Generated by gencpp from file marti_nav_msgs/RouteSpeedArray.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_ROUTESPEEDARRAY_H
#define MARTI_NAV_MSGS_MESSAGE_ROUTESPEEDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marti_nav_msgs/RouteSpeed.h>

namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct RouteSpeedArray_
{
  typedef RouteSpeedArray_<ContainerAllocator> Type;

  RouteSpeedArray_()
    : header()
    , speeds()  {
    }
  RouteSpeedArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speeds(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >::other >  _speeds_type;
  _speeds_type speeds;





  typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> const> ConstPtr;

}; // struct RouteSpeedArray_

typedef ::marti_nav_msgs::RouteSpeedArray_<std::allocator<void> > RouteSpeedArray;

typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeedArray > RouteSpeedArrayPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::RouteSpeedArray const> RouteSpeedArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.speeds == rhs.speeds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5b2e8db78eaab7eafdb3ecf8d4e017f";
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5b2e8db78eaab7eULL;
  static const uint64_t static_value2 = 0xafdb3ecf8d4e017fULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/RouteSpeedArray";
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# List of target speeds along a route.\n"
"\n"
"Header header        # only stamp used\n"
"\n"
"RouteSpeed[] speeds\n"
"# List of speeds along a route. The interpretation of the list is\n"
"# application dependent.  It may represent a list of unrelated speeds,\n"
"# a distance vs speed curve along a route, etc.\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marti_nav_msgs/RouteSpeed\n"
"# Speed at a position along route\n"
"\n"
"Header  header   # only stamp used\n"
"string  id       # unique ID of nearest point\n"
"float32 distance # forward along route, in meters from point identified by id\n"
"                 # field (negative values indicate the distance is backward\n"
"                 # along the route)\n"
"float32 speed    # desired speed at the specified position\n"
;
  }

  static const char* value(const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speeds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RouteSpeedArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::RouteSpeedArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speeds[]" << std::endl;
    for (size_t i = 0; i < v.speeds.size(); ++i)
    {
      s << indent << "  speeds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marti_nav_msgs::RouteSpeed_<ContainerAllocator> >::stream(s, indent + "    ", v.speeds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_ROUTESPEEDARRAY_H
