// Generated by gencpp from file marti_nav_msgs/SaveRoute.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_SAVEROUTE_H
#define MARTI_NAV_MSGS_MESSAGE_SAVEROUTE_H

#include <ros/service_traits.h>


#include <marti_nav_msgs/SaveRouteRequest.h>
#include <marti_nav_msgs/SaveRouteResponse.h>


namespace marti_nav_msgs
{

struct SaveRoute
{

typedef SaveRouteRequest Request;
typedef SaveRouteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveRoute
} // namespace marti_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marti_nav_msgs::SaveRoute > {
  static const char* value()
  {
    return "bf5efc6eabcf9ab3979d72995521ce7b";
  }

  static const char* value(const ::marti_nav_msgs::SaveRoute&) { return value(); }
};

template<>
struct DataType< ::marti_nav_msgs::SaveRoute > {
  static const char* value()
  {
    return "marti_nav_msgs/SaveRoute";
  }

  static const char* value(const ::marti_nav_msgs::SaveRoute&) { return value(); }
};


// service_traits::MD5Sum< ::marti_nav_msgs::SaveRouteRequest> should match
// service_traits::MD5Sum< ::marti_nav_msgs::SaveRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::SaveRouteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::SaveRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRouteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::SaveRouteRequest> should match
// service_traits::DataType< ::marti_nav_msgs::SaveRoute >
template<>
struct DataType< ::marti_nav_msgs::SaveRouteRequest>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::SaveRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRouteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marti_nav_msgs::SaveRouteResponse> should match
// service_traits::MD5Sum< ::marti_nav_msgs::SaveRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::SaveRouteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::SaveRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRouteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::SaveRouteResponse> should match
// service_traits::DataType< ::marti_nav_msgs::SaveRoute >
template<>
struct DataType< ::marti_nav_msgs::SaveRouteResponse>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::SaveRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRouteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_SAVEROUTE_H
