// Generated by gencpp from file marti_nav_msgs/SaveRecordedRoute.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_SAVERECORDEDROUTE_H
#define MARTI_NAV_MSGS_MESSAGE_SAVERECORDEDROUTE_H

#include <ros/service_traits.h>


#include <marti_nav_msgs/SaveRecordedRouteRequest.h>
#include <marti_nav_msgs/SaveRecordedRouteResponse.h>


namespace marti_nav_msgs
{

struct SaveRecordedRoute
{

typedef SaveRecordedRouteRequest Request;
typedef SaveRecordedRouteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveRecordedRoute
} // namespace marti_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marti_nav_msgs::SaveRecordedRoute > {
  static const char* value()
  {
    return "1d60247b7d1b53a7f54ab7ec855129c5";
  }

  static const char* value(const ::marti_nav_msgs::SaveRecordedRoute&) { return value(); }
};

template<>
struct DataType< ::marti_nav_msgs::SaveRecordedRoute > {
  static const char* value()
  {
    return "marti_nav_msgs/SaveRecordedRoute";
  }

  static const char* value(const ::marti_nav_msgs::SaveRecordedRoute&) { return value(); }
};


// service_traits::MD5Sum< ::marti_nav_msgs::SaveRecordedRouteRequest> should match
// service_traits::MD5Sum< ::marti_nav_msgs::SaveRecordedRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::SaveRecordedRouteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::SaveRecordedRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRecordedRouteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::SaveRecordedRouteRequest> should match
// service_traits::DataType< ::marti_nav_msgs::SaveRecordedRoute >
template<>
struct DataType< ::marti_nav_msgs::SaveRecordedRouteRequest>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::SaveRecordedRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRecordedRouteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marti_nav_msgs::SaveRecordedRouteResponse> should match
// service_traits::MD5Sum< ::marti_nav_msgs::SaveRecordedRoute >
template<>
struct MD5Sum< ::marti_nav_msgs::SaveRecordedRouteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::SaveRecordedRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRecordedRouteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::SaveRecordedRouteResponse> should match
// service_traits::DataType< ::marti_nav_msgs::SaveRecordedRoute >
template<>
struct DataType< ::marti_nav_msgs::SaveRecordedRouteResponse>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::SaveRecordedRoute >::value();
  }
  static const char* value(const ::marti_nav_msgs::SaveRecordedRouteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_SAVERECORDEDROUTE_H
