// Generated by gencpp from file marti_nav_msgs/SetRouteRequest.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_SETROUTEREQUEST_H
#define MARTI_NAV_MSGS_MESSAGE_SETROUTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct SetRouteRequest_
{
  typedef SetRouteRequest_<ContainerAllocator> Type;

  SetRouteRequest_()
    : guid()
    , repeat(false)  {
    }
  SetRouteRequest_(const ContainerAllocator& _alloc)
    : guid(_alloc)
    , repeat(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _guid_type;
  _guid_type guid;

   typedef uint8_t _repeat_type;
  _repeat_type repeat;





  typedef boost::shared_ptr< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRouteRequest_

typedef ::marti_nav_msgs::SetRouteRequest_<std::allocator<void> > SetRouteRequest;

typedef boost::shared_ptr< ::marti_nav_msgs::SetRouteRequest > SetRouteRequestPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::SetRouteRequest const> SetRouteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.guid == rhs.guid &&
    lhs.repeat == rhs.repeat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8b45ce32694aa3d4b43319418424d4d";
  }

  static const char* value(const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8b45ce32694aa3dULL;
  static const uint64_t static_value2 = 0x4b43319418424d4dULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/SetRouteRequest";
  }

  static const char* value(const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"string guid\n"
"bool repeat\n"
"\n"
;
  }

  static const char* value(const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.guid);
      stream.next(m.repeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRouteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::SetRouteRequest_<ContainerAllocator>& v)
  {
    s << indent << "guid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.guid);
    s << indent << "repeat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.repeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_SETROUTEREQUEST_H
