// Generated by gencpp from file marti_nav_msgs/UpdateRouteMetadata.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_UPDATEROUTEMETADATA_H
#define MARTI_NAV_MSGS_MESSAGE_UPDATEROUTEMETADATA_H

#include <ros/service_traits.h>


#include <marti_nav_msgs/UpdateRouteMetadataRequest.h>
#include <marti_nav_msgs/UpdateRouteMetadataResponse.h>


namespace marti_nav_msgs
{

struct UpdateRouteMetadata
{

typedef UpdateRouteMetadataRequest Request;
typedef UpdateRouteMetadataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateRouteMetadata
} // namespace marti_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::marti_nav_msgs::UpdateRouteMetadata > {
  static const char* value()
  {
    return "680bbce4d545516006965d175dfcdb08";
  }

  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadata&) { return value(); }
};

template<>
struct DataType< ::marti_nav_msgs::UpdateRouteMetadata > {
  static const char* value()
  {
    return "marti_nav_msgs/UpdateRouteMetadata";
  }

  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadata&) { return value(); }
};


// service_traits::MD5Sum< ::marti_nav_msgs::UpdateRouteMetadataRequest> should match
// service_traits::MD5Sum< ::marti_nav_msgs::UpdateRouteMetadata >
template<>
struct MD5Sum< ::marti_nav_msgs::UpdateRouteMetadataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::UpdateRouteMetadata >::value();
  }
  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::UpdateRouteMetadataRequest> should match
// service_traits::DataType< ::marti_nav_msgs::UpdateRouteMetadata >
template<>
struct DataType< ::marti_nav_msgs::UpdateRouteMetadataRequest>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::UpdateRouteMetadata >::value();
  }
  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::marti_nav_msgs::UpdateRouteMetadataResponse> should match
// service_traits::MD5Sum< ::marti_nav_msgs::UpdateRouteMetadata >
template<>
struct MD5Sum< ::marti_nav_msgs::UpdateRouteMetadataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::marti_nav_msgs::UpdateRouteMetadata >::value();
  }
  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::marti_nav_msgs::UpdateRouteMetadataResponse> should match
// service_traits::DataType< ::marti_nav_msgs::UpdateRouteMetadata >
template<>
struct DataType< ::marti_nav_msgs::UpdateRouteMetadataResponse>
{
  static const char* value()
  {
    return DataType< ::marti_nav_msgs::UpdateRouteMetadata >::value();
  }
  static const char* value(const ::marti_nav_msgs::UpdateRouteMetadataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_UPDATEROUTEMETADATA_H
