// Generated by gencpp from file marti_nav_msgs/VehicleControl.msg
// DO NOT EDIT!


#ifndef MARTI_NAV_MSGS_MESSAGE_VEHICLECONTROL_H
#define MARTI_NAV_MSGS_MESSAGE_VEHICLECONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marti_nav_msgs
{
template <class ContainerAllocator>
struct VehicleControl_
{
  typedef VehicleControl_<ContainerAllocator> Type;

  VehicleControl_()
    : header()
    , engine(0)
    , gear(0)
    , steering(0.0)
    , throttle(0.0)
    , brake(0.0)
    , steering_position(0)
    , gb_position(0)  {
    }
  VehicleControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , engine(0)
    , gear(0)
    , steering(0.0)
    , throttle(0.0)
    , brake(0.0)
    , steering_position(0)
    , gb_position(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _engine_type;
  _engine_type engine;

   typedef int32_t _gear_type;
  _gear_type gear;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _brake_type;
  _brake_type brake;

   typedef int16_t _steering_position_type;
  _steering_position_type steering_position;

   typedef int16_t _gb_position_type;
  _gb_position_type gb_position;





  typedef boost::shared_ptr< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleControl_

typedef ::marti_nav_msgs::VehicleControl_<std::allocator<void> > VehicleControl;

typedef boost::shared_ptr< ::marti_nav_msgs::VehicleControl > VehicleControlPtr;
typedef boost::shared_ptr< ::marti_nav_msgs::VehicleControl const> VehicleControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_nav_msgs::VehicleControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_nav_msgs::VehicleControl_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::VehicleControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.engine == rhs.engine &&
    lhs.gear == rhs.gear &&
    lhs.steering == rhs.steering &&
    lhs.throttle == rhs.throttle &&
    lhs.brake == rhs.brake &&
    lhs.steering_position == rhs.steering_position &&
    lhs.gb_position == rhs.gb_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_nav_msgs::VehicleControl_<ContainerAllocator1> & lhs, const ::marti_nav_msgs::VehicleControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afc6b0b97f62f744f4b35119ffb6e337";
  }

  static const char* value(const ::marti_nav_msgs::VehicleControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafc6b0b97f62f744ULL;
  static const uint64_t static_value2 = 0xf4b35119ffb6e337ULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_nav_msgs/VehicleControl";
  }

  static const char* value(const ::marti_nav_msgs::VehicleControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header 		header\n"
"\n"
"int32 		engine\n"
"int32 		gear\n"
"float64 	steering\n"
"float64 	throttle\n"
"float64 	brake\n"
"int16 		steering_position\n"
"int16 		gb_position\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::marti_nav_msgs::VehicleControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.engine);
      stream.next(m.gear);
      stream.next(m.steering);
      stream.next(m.throttle);
      stream.next(m.brake);
      stream.next(m.steering_position);
      stream.next(m.gb_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_nav_msgs::VehicleControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_nav_msgs::VehicleControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "engine: ";
    Printer<int32_t>::stream(s, indent + "  ", v.engine);
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "brake: ";
    Printer<double>::stream(s, indent + "  ", v.brake);
    s << indent << "steering_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering_position);
    s << indent << "gb_position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gb_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_NAV_MSGS_MESSAGE_VEHICLECONTROL_H
