# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from marti_nav_msgs/Wgs84Sample.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Wgs84Sample(genpy.Message):
  _md5sum = "5241cb1ac52fc7a58f710c9a9774badc"
  _type = "marti_nav_msgs/Wgs84Sample"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# This message contains an absolute position measurement (in
# spherical/WGS-84 coordinates) and the corresponding sensor
# (e.g. antenna) location in a vehicle's relative odometry coordinate
# frame.

Header header
# The header contains the /tf name of the relative odometry frame and
# the timestamp of the measurement.

geometry_msgs/Point odom
# The position of the sample in the relative odometry frame.

geometry_msgs/Point wgs84
# The WGS84 measurement (x = longitude in decimal degrees, y =
# latitude in decimal degrees, z = altitude over the reference
# ellipsoid in meters)

float64[9] wgs84_covariance
# An estimate of WGS-84 measurement's covariance.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','odom','wgs84','wgs84_covariance']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','geometry_msgs/Point','float64[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,odom,wgs84,wgs84_covariance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Wgs84Sample, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.odom is None:
        self.odom = geometry_msgs.msg.Point()
      if self.wgs84 is None:
        self.wgs84 = geometry_msgs.msg.Point()
      if self.wgs84_covariance is None:
        self.wgs84_covariance = [0.] * 9
    else:
      self.header = std_msgs.msg.Header()
      self.odom = geometry_msgs.msg.Point()
      self.wgs84 = geometry_msgs.msg.Point()
      self.wgs84_covariance = [0.] * 9

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.odom.x, _x.odom.y, _x.odom.z, _x.wgs84.x, _x.wgs84.y, _x.wgs84.z))
      buff.write(_get_struct_9d().pack(*self.wgs84_covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.odom is None:
        self.odom = geometry_msgs.msg.Point()
      if self.wgs84 is None:
        self.wgs84 = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.odom.x, _x.odom.y, _x.odom.z, _x.wgs84.x, _x.wgs84.y, _x.wgs84.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 72
      self.wgs84_covariance = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.odom.x, _x.odom.y, _x.odom.z, _x.wgs84.x, _x.wgs84.y, _x.wgs84.z))
      buff.write(self.wgs84_covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.odom is None:
        self.odom = geometry_msgs.msg.Point()
      if self.wgs84 is None:
        self.wgs84 = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.odom.x, _x.odom.y, _x.odom.z, _x.wgs84.x, _x.wgs84.y, _x.wgs84.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 72
      self.wgs84_covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
