// Generated by gencpp from file marti_common_msgs/KeyValueArray.msg
// DO NOT EDIT!


#ifndef MARTI_COMMON_MSGS_MESSAGE_KEYVALUEARRAY_H
#define MARTI_COMMON_MSGS_MESSAGE_KEYVALUEARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marti_common_msgs/KeyValue.h>

namespace marti_common_msgs
{
template <class ContainerAllocator>
struct KeyValueArray_
{
  typedef KeyValueArray_<ContainerAllocator> Type;

  KeyValueArray_()
    : header()
    , items()  {
    }
  KeyValueArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , items(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::marti_common_msgs::KeyValue_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::marti_common_msgs::KeyValue_<ContainerAllocator> >::other >  _items_type;
  _items_type items;





  typedef boost::shared_ptr< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> const> ConstPtr;

}; // struct KeyValueArray_

typedef ::marti_common_msgs::KeyValueArray_<std::allocator<void> > KeyValueArray;

typedef boost::shared_ptr< ::marti_common_msgs::KeyValueArray > KeyValueArrayPtr;
typedef boost::shared_ptr< ::marti_common_msgs::KeyValueArray const> KeyValueArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_common_msgs::KeyValueArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_common_msgs::KeyValueArray_<ContainerAllocator1> & lhs, const ::marti_common_msgs::KeyValueArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.items == rhs.items;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_common_msgs::KeyValueArray_<ContainerAllocator1> & lhs, const ::marti_common_msgs::KeyValueArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b303032d5c2c08f75f9a40a839cb16c";
  }

  static const char* value(const ::marti_common_msgs::KeyValueArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b303032d5c2c08fULL;
  static const uint64_t static_value2 = 0x75f9a40a839cb16cULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_common_msgs/KeyValueArray";
  }

  static const char* value(const ::marti_common_msgs::KeyValueArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A generic message for publishing a list of key value pairs directly.\n"
"\n"
"Header header\n"
"\n"
"KeyValue[] items\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marti_common_msgs/KeyValue\n"
"# An arbitrary key-value pair\n"
"\n"
"string key\n"
"string value\n"
;
  }

  static const char* value(const ::marti_common_msgs::KeyValueArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.items);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyValueArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_common_msgs::KeyValueArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_common_msgs::KeyValueArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "items[]" << std::endl;
    for (size_t i = 0; i < v.items.size(); ++i)
    {
      s << indent << "  items[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marti_common_msgs::KeyValue_<ContainerAllocator> >::stream(s, indent + "    ", v.items[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_COMMON_MSGS_MESSAGE_KEYVALUEARRAY_H
