// Generated by gencpp from file marti_sensor_msgs/Exposure.msg
// DO NOT EDIT!


#ifndef MARTI_SENSOR_MSGS_MESSAGE_EXPOSURE_H
#define MARTI_SENSOR_MSGS_MESSAGE_EXPOSURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace marti_sensor_msgs
{
template <class ContainerAllocator>
struct Exposure_
{
  typedef Exposure_<ContainerAllocator> Type;

  Exposure_()
    : header()
    , value(0)  {
    }
  Exposure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::marti_sensor_msgs::Exposure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_sensor_msgs::Exposure_<ContainerAllocator> const> ConstPtr;

}; // struct Exposure_

typedef ::marti_sensor_msgs::Exposure_<std::allocator<void> > Exposure;

typedef boost::shared_ptr< ::marti_sensor_msgs::Exposure > ExposurePtr;
typedef boost::shared_ptr< ::marti_sensor_msgs::Exposure const> ExposureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_sensor_msgs::Exposure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_sensor_msgs::Exposure_<ContainerAllocator1> & lhs, const ::marti_sensor_msgs::Exposure_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_sensor_msgs::Exposure_<ContainerAllocator1> & lhs, const ::marti_sensor_msgs::Exposure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_sensor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_sensor_msgs::Exposure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_sensor_msgs::Exposure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_sensor_msgs::Exposure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85b556f2af6a79c3e57c029d50b2ad45";
  }

  static const char* value(const ::marti_sensor_msgs::Exposure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85b556f2af6a79c3ULL;
  static const uint64_t static_value2 = 0xe57c029d50b2ad45ULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_sensor_msgs/Exposure";
  }

  static const char* value(const ::marti_sensor_msgs::Exposure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains an an exposure value along with a\n"
"# message header.  This message is to keep the same format\n"
"# that we have with Image and CameraInfo.\n"
"\n"
"Header header                    # Header timestamp is the time when all \n"
"                                 # images were acquired and synchronized.\n"
"                                 # Header frame_id is the count of these\n"
"                                 # messages sent since the start.\n"
"                               \n"
"uint64 value                     # Exposure value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::marti_sensor_msgs::Exposure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Exposure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_sensor_msgs::Exposure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_sensor_msgs::Exposure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_SENSOR_MSGS_MESSAGE_EXPOSURE_H
