// Generated by gencpp from file marti_sensor_msgs/WheelEncoderSet.msg
// DO NOT EDIT!


#ifndef MARTI_SENSOR_MSGS_MESSAGE_WHEELENCODERSET_H
#define MARTI_SENSOR_MSGS_MESSAGE_WHEELENCODERSET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marti_sensor_msgs/WheelEncoder.h>

namespace marti_sensor_msgs
{
template <class ContainerAllocator>
struct WheelEncoderSet_
{
  typedef WheelEncoderSet_<ContainerAllocator> Type;

  WheelEncoderSet_()
    : header()
    , encoders()  {
    }
  WheelEncoderSet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoders(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::marti_sensor_msgs::WheelEncoder_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::marti_sensor_msgs::WheelEncoder_<ContainerAllocator> >::other >  _encoders_type;
  _encoders_type encoders;





  typedef boost::shared_ptr< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> const> ConstPtr;

}; // struct WheelEncoderSet_

typedef ::marti_sensor_msgs::WheelEncoderSet_<std::allocator<void> > WheelEncoderSet;

typedef boost::shared_ptr< ::marti_sensor_msgs::WheelEncoderSet > WheelEncoderSetPtr;
typedef boost::shared_ptr< ::marti_sensor_msgs::WheelEncoderSet const> WheelEncoderSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator1> & lhs, const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.encoders == rhs.encoders;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator1> & lhs, const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marti_sensor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1169b74ddf14d2e1ad1aa65311182d9";
  }

  static const char* value(const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1169b74ddf14d2eULL;
  static const uint64_t static_value2 = 0x1ad1aa65311182d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marti_sensor_msgs/WheelEncoderSet";
  }

  static const char* value(const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"WheelEncoder[] encoders\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marti_sensor_msgs/WheelEncoder\n"
"# Frequency from wheel encoder\n"
"#  If directional (below) is True, positive frequency means forward, and\n"
"#   negative frequency means backward.\n"
"#  If directional is False, frequency is non-negative and has no directional\n"
"#   information\n"
"float64 frequency\n"
"\n"
"# True if frequency sign is significant; false else\n"
"bool directional\n"
"\n"
"# ID of the wheel with which this data is associated\n"
"uint8 id\n"
;
  }

  static const char* value(const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoders);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelEncoderSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marti_sensor_msgs::WheelEncoderSet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoders[]" << std::endl;
    for (size_t i = 0; i < v.encoders.size(); ++i)
    {
      s << indent << "  encoders[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marti_sensor_msgs::WheelEncoder_<ContainerAllocator> >::stream(s, indent + "    ", v.encoders[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARTI_SENSOR_MSGS_MESSAGE_WHEELENCODERSET_H
