(cl:defpackage mapviz-srv
  (:use )
  (:export
   "ADDMAPVIZDISPLAY"
   "<ADDMAPVIZDISPLAY-REQUEST>"
   "ADDMAPVIZDISPLAY-REQUEST"
   "<ADDMAPVIZDISPLAY-RESPONSE>"
   "ADDMAPVIZDISPLAY-RESPONSE"
  ))

