(cl:in-package marti_nav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          POSE-VAL
          POSE
          VELOCITY-VAL
          VELOCITY
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          LINEAR_ACCELERATION_COVARIANCE-VAL
          LINEAR_ACCELERATION_COVARIANCE
          POLYGON-VAL
          POLYGON
          LENGTH-VAL
          LENGTH
          LENGTH_QUALITY-VAL
          LENGTH_QUALITY
          WIDTH-VAL
          WIDTH
          WIDTH_QUALITY-VAL
          WIDTH_QUALITY
          CLASSIFICATION-VAL
          CLASSIFICATION
          CLASSIFICATION_QUALITY-VAL
          CLASSIFICATION_QUALITY
          EXISTENCE_PROBABILITY-VAL
          EXISTENCE_PROBABILITY
          AGE_DURATION-VAL
          AGE_DURATION
          PREDICTION_DURATION-VAL
          PREDICTION_DURATION
          ACTIVE-VAL
          ACTIVE
))