(cl:in-package marti_nav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEGMENT_TYPE-VAL
          SEGMENT_TYPE
          LENGTH-VAL
          LENGTH
          START_SPEED-VAL
          START_SPEED
          END_SPEED-VAL
          END_SPEED
          STARTX-VAL
          STARTX
          STARTY-VAL
          STARTY
          ENDX-VAL
          ENDX
          ENDY-VAL
          ENDY
          THETA0-VAL
          THETA0
          A1-VAL
          A1
          A2-VAL
          A2
          K0-VAL
          K0
          C1-VAL
          C1
          C2-VAL
          C2
          BEHAVIOR-VAL
          BEHAVIOR
          CREEP-VAL
          CREEP
          ACC-VAL
          ACC
          REVERSE-VAL
          REVERSE
          VEHICLE_TRACK-VAL
          VEHICLE_TRACK
          TRANSMITTED-VAL
          TRANSMITTED
          AUXTRANSMITTED-VAL
          AUXTRANSMITTED
          THETA_END-VAL
          THETA_END
          K_END-VAL
          K_END
          SEG_LEN-VAL
          SEG_LEN
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          MAX_ERROR-VAL
          MAX_ERROR
          MAX_SMOOTH-VAL
          MAX_SMOOTH
          MAX_CURV-VAL
          MAX_CURV
          POSSIBLE_POINTS-VAL
          POSSIBLE_POINTS
          BEXITSEGMENT-VAL
          BEXITSEGMENT
))