// Generated by gencpp from file mapviz/AddMapvizDisplayResponse.msg
// DO NOT EDIT!


#ifndef MAPVIZ_MESSAGE_ADDMAPVIZDISPLAYRESPONSE_H
#define MAPVIZ_MESSAGE_ADDMAPVIZDISPLAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mapviz
{
template <class ContainerAllocator>
struct AddMapvizDisplayResponse_
{
  typedef AddMapvizDisplayResponse_<ContainerAllocator> Type;

  AddMapvizDisplayResponse_()
    : success(false)
    , message()  {
    }
  AddMapvizDisplayResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddMapvizDisplayResponse_

typedef ::mapviz::AddMapvizDisplayResponse_<std::allocator<void> > AddMapvizDisplayResponse;

typedef boost::shared_ptr< ::mapviz::AddMapvizDisplayResponse > AddMapvizDisplayResponsePtr;
typedef boost::shared_ptr< ::mapviz::AddMapvizDisplayResponse const> AddMapvizDisplayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator1> & lhs, const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator1> & lhs, const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mapviz

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapviz/AddMapvizDisplayResponse";
  }

  static const char* value(const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool   success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddMapvizDisplayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapviz::AddMapvizDisplayResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPVIZ_MESSAGE_ADDMAPVIZDISPLAYRESPONSE_H
